title: Synepis dev blog
email: argo.synepis@gmail.com 
description: Development blog, mostly tidbits about linux, Golang, network & systems programming.
github_username: synepis 

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
